const SUBJECT_LIST = [
  'Mathematics',
  'English Language',
  'Biology',
  'Chemistry',
  'Physics',
  'History',
  'Geography',
  'Economics',
  'Accounting',
  'Marketing',
  'Technical Drawing',
  'Data Processing',
  'Government',
  'Literature in English',
  'Civic Education',
  'Agricultural Science',
  'Computer Studies',
  'Further Mathematics',
  'French',
  'Technical Drawing',
  'Basic Science',
  'Basic Technology',
  'National Values',
  'Vocational Aptitude',
  'Pre-Vocational Aptitude',
  'Social Studies',
  'Home Economics',
  'Physical and Health Education',
  // 'Christian Religious Studies',
  // 'Islamic Religious Studies',
  'Religious Studies',
  'Music',
  'Fine Arts',
  'Creative Arts',
  'Commerce',
  'General Science',
  'Business Studies',
  'Quantitative Reasoning',
  'Verbal Reasoning',
  'Literacy',
  'Numeracy',
  'Discovery',
  'Rhymes',
  'Cultural and Creative Arts',
  'Social and Health Habits',
  'Phonics',
  'Phonics and Diction',
  'Elocution',
];
